#!/usr/bin/env python3
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "scripts"))

from robonex_common import load_urdf, fmt, ROOT
from robonex_serial import DEG, SERIAL_JOINTS, DAMPING

OUT = os.path.join(ROOT, "isaac", "robonex_serial.urdf")

MESH_URI = "../meshes/%s"

MATERIALS = (("black", "0.05 0.05 0.05 1.0"), ("gray", "0.647 0.647 0.647 1.0"))


def emit_link(o, name, lk):
    o.append('  <link name="%s">' % name)

    if lk.mass > 0.0:
        ixx, ixy, ixz, iyy, iyz, izz = lk.inertia
        o.append("    <inertial>")
        o.append('      <origin xyz="%s" rpy="0 0 0"/>' % fmt(lk.com))
        o.append('      <mass value="%.6f"/>' % lk.mass)
        o.append('      <inertia ixx="%.8f" ixy="%.8f" ixz="%.8f"'
                 ' iyy="%.8f" iyz="%.8f" izz="%.8f"/>'
                 % (ixx, ixy, ixz, iyy, iyz, izz))
        o.append("    </inertial>")

    for g in lk.visuals:
        colour = "gray" if g.mesh.startswith("rs0") else "black"
        o.append("    <visual>")
        o.append('      <origin xyz="%s" rpy="%s"/>' % (fmt(g.xyz), fmt(g.rpy)))
        o.append("      <geometry>")
        o.append('        <mesh filename="%s" scale="%s"/>'
                 % (MESH_URI % g.mesh, fmt(g.scale)))
        o.append("      </geometry>")
        o.append('      <material name="%s"/>' % colour)
        o.append("    </visual>")

    # Collision stays the visual mesh here, unlike the Gazebo build's fitted
    # boxes: Isaac's importer runs its own convex decomposition, so handing it
    # the real shape gives a better hull than pre-approximating with a box.
    for g in lk.visuals:
        o.append("    <collision>")
        o.append('      <origin xyz="%s" rpy="%s"/>' % (fmt(g.xyz), fmt(g.rpy)))
        o.append("      <geometry>")
        o.append('        <mesh filename="%s" scale="%s"/>'
                 % (MESH_URI % g.mesh, fmt(g.scale)))
        o.append("      </geometry>")
        o.append("    </collision>")

    o.append("  </link>")
    o.append("")


# Knee crank -> shin is a single-input coupling (one motor, one output), so a
# linear mimic constraint is a reasonable shape for it even though the real
# ratio isn't constant (0.21..1.23 across travel - see scripts/robonex_serial.py).
# 0.705 is the local slope at the home pose, so this is exact near neutral
# stance and drifts away from it, same caveat as the transmission numbers
# already baked into SERIAL_JOINTS.
#
# The ankle differential (2 motors -> roll+pitch) is NOT single-input, so it
# can't be expressed as one mimic constraint - left frozen, as in the Gazebo
# build.
MIMIC = {
    "l_knee_pitch_joint": ("l_knee_joint", 0.705),
    "r_knee_pitch_joint": ("r_knee_joint", 0.705),
}


def emit_joint(o, j):
    spec = SERIAL_JOINTS.get(j.name)
    mimic = MIMIC.get(j.name)
    # A mimic constraint needs an actual DOF to drive - "fixed" has none, so
    # a mimicked crank has to stay revolute even though it isn't independently
    # actuated (no SERIAL_JOINTS entry). Its own measured axis/limits (already
    # applied to urdf/robonex.urdf) carry straight through.
    kind = "revolute" if (spec or mimic) else "fixed"
    o.append('  <joint name="%s" type="%s">' % (j.name, kind))
    o.append('    <parent link="%s"/>' % j.parent)
    o.append('    <child link="%s"/>' % j.child)
    o.append('    <origin xyz="%s" rpy="%s"/>' % (fmt(j.xyz), fmt(j.rpy)))
    if spec:
        effort, velocity, lo_deg, hi_deg = spec
        o.append('    <axis xyz="%s"/>' % fmt(j.axis))
        o.append('    <limit lower="%.6f" upper="%.6f" effort="%g" velocity="%g"/>'
                 % (lo_deg * DEG, hi_deg * DEG, effort, velocity))
        o.append('    <dynamics damping="%g" friction="0.0"/>' % DAMPING)
    elif mimic:
        o.append('    <axis xyz="%s"/>' % fmt(j.axis))
        o.append('    <limit lower="%.6f" upper="%.6f" effort="%g" velocity="%g"/>'
                 % (j.lower, j.upper, j.effort, j.velocity))
        o.append('    <dynamics damping="%g" friction="0.0"/>' % DAMPING)
    if mimic:
        ref, mult = mimic
        o.append('    <mimic joint="%s" multiplier="%g" offset="0"/>' % (ref, mult))
    o.append("  </joint>")
    o.append("")


def main():
    links, joints, base = load_urdf()

    o = []
    o.append('<?xml version="1.0"?>')
    o.append("<!-- generated by isaac/build_isaac_urdf.py - do not edit by hand -->")
    o.append("<!-- serial-equivalent: the crank/coupler joints are frozen and the")
    o.append("     joints their linkages drive are actuated directly instead. -->")
    o.append('<robot name="robonex">')
    o.append("")
    for name, rgba in MATERIALS:
        o.append('  <material name="%s"><color rgba="%s"/></material>' % (name, rgba))
    o.append("")

    for name, lk in links.items():
        emit_link(o, name, lk)
    for j in joints.values():
        emit_joint(o, j)

    o.append("</robot>")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(o) + "\n")

    frozen = [j.name for j in joints.values()
             if j.name not in SERIAL_JOINTS and j.name not in MIMIC]
    print("wrote %s" % OUT)
    print("  links            : %d  (total mass %.6f kg)"
          % (len(links), sum(lk.mass for lk in links.values())))
    print("  actuated / mimic / frozen : %d / %d / %d"
          % (len(SERIAL_JOINTS), len(MIMIC), len(frozen)))
    print("  mimic            : %s" % ", ".join(sorted(MIMIC)))
    print()
    print("  convert normally (no CLI flag controls this - IsaacLab's converter")
    print("  hardcodes convert_mimic_joints_to_normal_joints=False), then verify")
    print("  the mimic constraint actually landed before trusting it.")


if __name__ == "__main__":
    main()
